name: lesion_meter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  auto_route: ^8.1.3
  camera: ^0.10.6
  cross_connectivity: ^3.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_3d_controller: ^1.3.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.1
  image_picker: ^1.1.1
  injectable: ^2.4.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  multiple_image_camera: ^0.0.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: any
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/anims/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_gen:
  assets:
    enabled: true
  integrations:
    flutter_svg: true
